/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

// GLB export'ta Mesh446_1, Mesh446_2 gibi alt parçalar oluşur.
// Taban adını çıkartarak (Mesh446_2 → Mesh446) toplu eşleştirme yapıyoruz.
const getBaseName = (name) => name.replace(/_\d+$/, '');

// ✅ Yeşil yapılacak mesh TABAN adları — seçim modundan kopyala
const GREEN_MESHES = ["Mesh446", "Mesh1309"];


// t: 0..1 — how "night" it is (1 = pitch dark, 0 = bright day)
function getNightFactor(t) {
    // Same phase as DayNightCycle: 0.2–0.3 dawn, 0.7–0.8 dusk
    if (t < 0.15) return 1;
    if (t < 0.3) return 1 - (t - 0.15) / 0.15;
    if (t < 0.7) return 0;
    if (t < 0.85) return (t - 0.7) / 0.15;
    return 1;
}

const isGlassMesh = (child) => {
    const nameLower = (child.name || '').toLowerCase();
    const matName = (child.material?.name || '').toLowerCase();
    const byName = ['cam', 'glass', 'window', 'win', 'glazing', 'pencere'].some(k =>
        nameLower.includes(k) || matName.includes(k)
    );
    const byMat = child.material && (
        (child.material.transparent && child.material.opacity < 0.95) ||
        child.material.transmission > 0
    );
    return byName || byMat;
};

export function BuildingModel({ onSelectApartment, pickMode, selectedMeshes, onMeshPick, timeOfDay, ...props }) {
    const { nodes, scene } = useGLTF('http://127.0.0.1:8080/model.glb')

    const modelObject = nodes.Sketchfab_Scene || nodes.RootNode || scene;

    if (!modelObject) {
        console.error("Could not find a valid object in GLTF model!", nodes);
        return <group {...props} dispose={null}><mesh><boxGeometry /><meshStandardMaterial color="red" /></mesh></group>;
    }

    const clone = React.useMemo(() => modelObject ? modelObject.clone(true) : null, [modelObject]);

    // Orijinal materyalleri kaydet
    React.useEffect(() => {
        if (clone) {
            clone.traverse((child) => {
                if (child.isMesh) {
                    child.castShadow = false;
                    child.receiveShadow = false;
                    if (!child.userData.originalMaterial) {
                        child.userData.originalMaterial = child.material;
                    }
                }
            });
        }
    }, [clone]);

    // Renk güncelleme: showStatus, pickMode ve cam parlaması
    React.useEffect(() => {
        if (!clone) return;

        const nightFactor = getNightFactor(timeOfDay ?? 0.5);

        clone.traverse((child) => {
            if (child.isMesh) {
                const base = getBaseName(child.name);
                const isGreenStatic = props.showStatus && GREEN_MESHES.includes(base);
                const isGreenPicked = pickMode && selectedMeshes && selectedMeshes.includes(base);

                if (isGreenStatic || isGreenPicked) {
                    const greenMat = child.userData.originalMaterial
                        ? child.userData.originalMaterial.clone()
                        : new THREE.MeshStandardMaterial();
                    greenMat.color.set('#4caf50');
                    child.material = greenMat;
                } else if (isGlassMesh(child) && nightFactor > 0.01) {
                    // Warm window glow at night
                    if (!child.userData.windowMat) {
                        const base = child.userData.originalMaterial
                            ? child.userData.originalMaterial.clone()
                            : new THREE.MeshStandardMaterial();
                        child.userData.windowMat = base;
                    }
                    const mat = child.userData.windowMat;
                    mat.emissive = new THREE.Color('#ffdd88');
                    mat.emissiveIntensity = nightFactor * 3.5;
                    child.material = mat;
                } else {
                    if (child.userData.originalMaterial) {
                        child.material = child.userData.originalMaterial;
                    }
                }
            }
        });
    }, [props.showStatus, pickMode, selectedMeshes, clone, timeOfDay]);

    return (
        <group {...props} dispose={null}>
            {clone && (
                <primitive
                    object={clone}
                    onClick={(e) => {
                        e.stopPropagation();
                        const name = e.object?.name;
                        if (!name) return;

                        if (pickMode && onMeshPick) {
                            // Seçim modu: tıklanan mesh'i listeye ekle/çıkar
                            onMeshPick(name);
                        } else if (onSelectApartment) {
                            // Sadece GREEN_MESHES'teki dairelere tıklandığında API'yi çağır
                            const base = getBaseName(name);
                            if (GREEN_MESHES.includes(base)) {
                                onSelectApartment(base);
                            }
                        }
                    }}
                />
            )}
        </group>
    )
}

useGLTF.preload('http://127.0.0.1:8080/model.glb')
